version: '3.9'

services:
  db:
    image: mysql:8.0.31
    ports:
      - "5432:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
      MYSQL_DATABASE: quest

  php:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: .docker
      dockerfile: php.Dockerfile
    ports:
      - "9000"
    volumes:
      - .:/quest
    working_dir: /quest
    command: >
      sh -c "composer install && bin/console doctrine:migrations:migrate --allow-no-migration && bin/console doctrine:fixture:load --no-interaction && php-fpm"
    depends_on:
      - db
    # todo: better healhcheck slow mysql
    restart: on-failure



  nginx:
    build:
      context: .docker
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
